### ISSUE TITLE
How can I translate the language to others

### ISSUE THREAD

**Issue by mrxf** [coman3/EloBuddy.Addons#11]
could you tell me how to change the language to others?

**Comment by commonsharp** [comment]
As far as I know Menu API does not support other languages
我不知道这是否有助于、You can see also bansharp encoding problem
http://webcache.googleusercontent.com/search?q=cache:https://www.joduska.me/forum/topic/150336-encoding-problemhelp-me-plst-t/&strip=1

**Comment by coman3** [comment]
Either way it's probably a good idea to add this feature. So french, German, etc. still works fine :smile: 

Im working on a language file as we speak and ill get back to you when i commit the change.

Thanks
